### ISSUE TITLE
Validation of resource identifier with empty id

### ISSUE THREAD

**Issue by lindyhopchris** [cloudcreativity/json-api#35]
```
[2017-05-17 06:10:53] testing.ERROR: exception 'CloudCreativity\JsonApi\Exceptions\RuntimeException' with message 'Id member is not a string or integer.' in /vagrant/vendor/cloudcreativity/json-api/src/Object/Helpers/IdentifiableTrait.php:86
Stack trace:
#0 /vagrant/vendor/cloudcreativity/json-api/src/Object/ResourceIdentifier.php(105): CloudCreativity\JsonApi\Object\ResourceIdentifier->getId()
#1 /vagrant/vendor/cloudcreativity/json-api/src/Store/IdentityMap.php(102): CloudCreativity\JsonApi\Object\ResourceIdentifier->toString()
#2 /vagrant/vendor/cloudcreativity/json-api/src/Store/IdentityMap.php(73): CloudCreativity\JsonApi\Store\IdentityMap->lookup(Object(CloudCreativity\JsonApi\Object\ResourceIdentifier))
#3 /vagrant/vendor/cloudcreativity/json-api/src/Store/Store.php(73): CloudCreativity\JsonApi\Store\IdentityMap->exists(Object(CloudCreativity\JsonApi\Object\ResourceIdentifier))
#4 /vagrant/vendor/cloudcreativity/json-api/src/Validators/AbstractRelationshipValidator.php(103): CloudCreativity\JsonApi\Store\Store->exists(Object(CloudCreativity\JsonApi\Object\ResourceIdentifier))
#5 /vagrant/vendor/cloudcreativity/json-api/src/Validators/AbstractRelationshipValidator.php(311): CloudCreativity\JsonApi\Validators\AbstractRelationshipValidator->doesExist(Object(CloudCreativity\JsonApi\Object\ResourceIdentifier))
#6 /vagrant/vendor/cloudcreativity/json-api/src/Validators/AbstractRelationshipValidator.php(192): CloudCreativity\JsonApi\Validators\AbstractRelationshipValidator->validateExists(Object(CloudCreativity\JsonApi\Object\ResourceIdentifier), 'ticket-type')
#7 /vagrant/vendor/cloudcreativity/json-api/src/Validators/RelationshipValidator.php(48): CloudCreativity\JsonApi\Validators\AbstractRelationshipValidator->validateHasOne(Object(CloudCreativity\JsonApi\Object\Relationship), NULL, 'ticket-type', Object(CloudCreativity\JsonApi\Object\Resource))
#8 /vagrant/vendor/cloudcreativity/json-api/src/Validators/RelationshipsValidator.php(211): CloudCreativity\JsonApi\Validators\RelationshipValidator->isValid(Object(CloudCreativity\JsonApi\Object\Relationship), NULL, 'ticket-type', Object(CloudCreativity\JsonApi\Object\Resource))
#9 /vagrant/vendor/cloudcreativity/json-api/src/Validators/RelationshipsValidator.php(157): CloudCreativity\JsonApi\Validators\RelationshipsValidator->validateRelationship('ticket-type', Object(CloudCreativity\JsonApi\Object\Relationships), Object(CloudCreativity\JsonApi\Object\Resource), NULL)
#10 /vagrant/vendor/cloudcreativity/json-api/src/Validators/ResourceValidator.php(234): CloudCreativity\JsonApi\Validators\RelationshipsValidator->isValid(Object(CloudCreativity\JsonApi\Object\Resource), NULL)
#11 /vagrant/vendor/cloudcreativity/json-api/src/Validators/ResourceValidator.php(111): CloudCreativity\JsonApi\Validators\ResourceValidator->validateRelationships(Object(CloudCreativity\JsonApi\Object\Resource), NULL)
#12 /vagrant/vendor/cloudcreativity/json-api/src/Validators/ResourceDocumentValidator.php(79): CloudCreativity\JsonApi\Validators\ResourceValidator->isValid(Object(CloudCreativity\JsonApi\Object\Resource), NULL)
#13 /vagrant/vendor/cloudcreativity/json-api/src/Http/Requests/RequestFactory.php(140): CloudCreativity\JsonApi\Validators\ResourceDocumentValidator->isValid(Object(CloudCreativity\JsonApi\Object\Document))
#14 /vagrant/vendor/cloudcreativity/json-api/src/Http/Requests/RequestFactory.php(127): CloudCreativity\JsonApi\Http\Requests\RequestFactory->validateDocument(Object(CloudCreativity\JsonApi\Object\Document), Object(CloudCreativity\LaravelJsonApi\Http\Requests\RequestInterpreter))
```

Believe the data submitted was a has-one relationship with data object that had correct type but id was a null value.

**Comment by GregPeden** [comment]
+1 to this, I just came here to report this as an issue for when the id on a relationship is null for a create or update payload.

I am not sure if this is spec-compliant or not, however worst-case it should return an error to the client. I would prefer that a null result be interpreted as "no relationship" but I am not an expert on if the JSON spec allows this.

**Comment by lindyhopchris** [comment]
It's definitely a bug. A resource identifier (type + id) should always reference a resource, so both would need to be provided. If "no relationship", then `null` should be provided instead of a resource identifier. 

I.e. for an "author" relationship, the relationships should be this for no relationship:

```json
{
  "author": { "data": null }
}
```

And this for a relationship:

```json
{
  "author": { "data": { "type": "users", "id": "1" } }
}
```

Should be getting this bug fixed in the next release.

**Comment by GregPeden** [comment]
Just to be clear, I am talking about sending a relationship as so:
```js
{
  "author": { "data": { "type": "users", "id": null } }
}
```

This generates a server error, and it probably shouldn't because we can't control what API users are doing.

I THINK you are intending the same above, but I just want to make sure we're on the same page.

**Comment by lindyhopchris** [comment]
Yes, that should be rejected as a bad request because it is not allowed by the spec - the resource identifier within it is incomplete.
